export const featuredContent = {
  id: "featured-1",
  title: "THE TRAITORS",
  description:
    "Season 1 · Welcome to The Traitors — a ruthless reality show hosted by Karan Johar, where 20 celebrities betray and deceive each other for a chance to win a massive cash prize. Trust no one.",
  backgroundImage: "/placeholder.svg?height=800&width=1400&text=THE+TRAITORS+Hero+Banner",
  episodeInfo: "NEW EPISODES THURSDAY 8 PM",
  newEpisodeInfo: "New episode Thursday",
  imdbRating: "8.2",
  year: 2024,
  rating: "TV-MA",
  duration: "8 episodes",
}

export const featuredOriginals = [
  {
    id: "original-1",
    title: "THE TRAITORS",
    thumbnail: "/placeholder.svg?height=315&width=560&text=THE+TRAITORS",
    badge: "TOP 10",
    isPrime: true,
    year: 2024,
    duration: "45m",
    rating: "8.2",
    genre: "Reality TV",
  },
  {
    id: "original-2",
    title: "ROMCON",
    thumbnail: "/placeholder.svg?height=315&width=560&text=ROMCON",
    badge: "NEW SERIES",
    isPrime: true,
    year: 2024,
    duration: "42m",
    rating: "7.8",
    genre: "Comedy",
  },
  {
    id: "original-3",
    title: "in transit",
    thumbnail: "/placeholder.svg?height=315&width=560&text=in+transit",
    badge: "NEW SERIES",
    isPrime: true,
    year: 2024,
    duration: "38m",
    rating: "8.5",
    genre: "Drama",
  },
  {
    id: "original-4",
    title: "CLARKSON'S FARM",
    thumbnail: "/placeholder.svg?height=315&width=560&text=CLARKSON'S+FARM",
    badge: "NEW SEASON",
    isPrime: true,
    year: 2024,
    duration: "52m",
    rating: "9.1",
    genre: "Documentary",
  },
  {
    id: "original-5",
    title: "MOTORHEADS",
    thumbnail: "/placeholder.svg?height=315&width=560&text=MOTORHEADS",
    badge: "NEW SERIES",
    isPrime: true,
    year: 2024,
    duration: "44m",
    rating: "7.9",
    genre: "Action",
  },
]

export const recentlyAdded = [
  {
    id: "recent-1",
    title: "The Bear",
    thumbnail: "/placeholder.svg?height=315&width=560&text=The+Bear",
    isPrime: true,
    year: 2024,
    duration: "30m",
    rating: "8.7",
    genre: "Comedy-Drama",
  },
  {
    id: "recent-2",
    title: "Fallout",
    thumbnail: "/placeholder.svg?height=315&width=560&text=Fallout",
    isPrime: true,
    year: 2024,
    duration: "1h 5m",
    rating: "8.4",
    genre: "Sci-Fi",
  },
  {
    id: "recent-3",
    title: "Mr. & Mrs. Smith",
    thumbnail: "/placeholder.svg?height=315&width=560&text=Mr+Mrs+Smith",
    isPrime: true,
    year: 2024,
    duration: "55m",
    rating: "8.1",
    genre: "Action",
  },
  {
    id: "recent-4",
    title: "The Power",
    thumbnail: "/placeholder.svg?height=315&width=560&text=The+Power",
    isPrime: true,
    year: 2024,
    duration: "58m",
    rating: "7.6",
    genre: "Drama",
  },
  {
    id: "recent-5",
    title: "Air",
    thumbnail: "/placeholder.svg?height=315&width=560&text=Air+Movie",
    isPrime: true,
    year: 2023,
    duration: "1h 51m",
    rating: "7.4",
    genre: "Biography",
  },
]

export const popularMovies = [
  {
    id: "movie-1",
    title: "The Tomorrow War",
    thumbnail: "/placeholder.svg?height=315&width=560&text=The+Tomorrow+War",
    badge: "TOP 10",
    isPrime: true,
    year: 2021,
    duration: "2h 18m",
    rating: "6.5",
    genre: "Action",
  },
  {
    id: "movie-2",
    title: "Sound of Metal",
    thumbnail: "/placeholder.svg?height=315&width=560&text=Sound+of+Metal",
    isPrime: true,
    year: 2020,
    duration: "2h 0m",
    rating: "7.7",
    genre: "Drama",
  },
  {
    id: "movie-3",
    title: "Coming 2 America",
    thumbnail: "/placeholder.svg?height=315&width=560&text=Coming+2+America",
    isPrime: true,
    year: 2021,
    duration: "1h 50m",
    rating: "5.3",
    genre: "Comedy",
  },
  {
    id: "movie-4",
    title: "The Power of the Dog",
    thumbnail: "/placeholder.svg?height=315&width=560&text=Power+of+Dog",
    isPrime: true,
    year: 2021,
    duration: "2h 8m",
    rating: "6.8",
    genre: "Drama",
  },
  {
    id: "movie-5",
    title: "Being the Ricardos",
    thumbnail: "/placeholder.svg?height=315&width=560&text=Being+Ricardos",
    isPrime: true,
    year: 2021,
    duration: "2h 11m",
    rating: "6.5",
    genre: "Biography",
  },
]

export const topTVShows = [
  {
    id: "tv-1",
    title: "The Boys",
    thumbnail: "/placeholder.svg?height=315&width=560&text=The+Boys",
    badge: "TOP 10",
    isPrime: true,
    year: 2024,
    duration: "1h 2m",
    rating: "8.7",
    genre: "Superhero",
  },
  {
    id: "tv-2",
    title: "The Marvelous Mrs. Maisel",
    thumbnail: "/placeholder.svg?height=315&width=560&text=Mrs+Maisel",
    isPrime: true,
    year: 2023,
    duration: "52m",
    rating: "8.7",
    genre: "Comedy-Drama",
  },
  {
    id: "tv-3",
    title: "Jack Ryan",
    thumbnail: "/placeholder.svg?height=315&width=560&text=Jack+Ryan",
    isPrime: true,
    year: 2023,
    duration: "1h 8m",
    rating: "8.0",
    genre: "Action",
  },
  {
    id: "tv-4",
    title: "The Wheel of Time",
    thumbnail: "/placeholder.svg?height=315&width=560&text=Wheel+of+Time",
    isPrime: true,
    year: 2023,
    duration: "1h 5m",
    rating: "7.1",
    genre: "Fantasy",
  },
  {
    id: "tv-5",
    title: "Citadel",
    thumbnail: "/placeholder.svg?height=315&width=560&text=Citadel",
    isPrime: true,
    year: 2023,
    duration: "58m",
    rating: "6.5",
    genre: "Spy",
  },
]

export const getContentById = (id: string) => {
  const allContent = [...recentlyAdded, ...popularMovies, ...topTVShows, ...featuredOriginals, featuredContent]
  return (
    allContent.find((item) => item.id === id) || {
      id,
      title: "Sample Content",
      description:
        "This is a sample description for the content. In a real application, this would be fetched from a database or API with detailed plot information and cast details.",
      thumbnail: "/placeholder.svg?height=315&width=560&text=Sample+Content",
      year: 2024,
      duration: "1h 30m",
      genre: "Drama, Thriller",
      rating: "TV-MA",
    }
  )
}

export const recommendedContent = [
  {
    id: "rec-1",
    title: "Similar Show 1",
    thumbnail: "/placeholder.svg?height=315&width=560&text=Similar+Show+1",
    isPrime: true,
    year: 2024,
    duration: "45m",
    rating: "8.3",
    genre: "Drama",
  },
  {
    id: "rec-2",
    title: "Similar Show 2",
    thumbnail: "/placeholder.svg?height=315&width=560&text=Similar+Show+2",
    isPrime: true,
    year: 2023,
    duration: "1h 2m",
    rating: "7.9",
    genre: "Thriller",
  },
  {
    id: "rec-3",
    title: "Similar Show 3",
    thumbnail: "/placeholder.svg?height=315&width=560&text=Similar+Show+3",
    isPrime: true,
    year: 2024,
    duration: "38m",
    rating: "8.1",
    genre: "Comedy",
  },
  {
    id: "rec-4",
    title: "Similar Show 4",
    thumbnail: "/placeholder.svg?height=315&width=560&text=Similar+Show+4",
    isPrime: true,
    year: 2024,
    duration: "52m",
    rating: "8.5",
    genre: "Action",
  },
]
