export const featuredContent = {
  id: "featured-1",
  title: "THE TRAITORS",
  description:
    "Season 1 · Welcome to The Traitors — a ruthless reality show hosted by Karan Johar, where 20 celebrities betray and deceive each other for a chance to win a massive cash prize. Trust no one.",
  backgroundImage: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/the+traitors.jpg",
  episodeInfo: "NEW EPISODES THURSDAY 8 PM",
  newEpisodeInfo: "New episode Thursday",
  imdbRating: "8.2",
  year: 2024,
  rating: "TV-MA",
  duration: "8 episodes",
}

export const featuredOriginals = [
  {
    id: "original-1",
    title: "THE TRAITORS",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/the+traitors.jpg",
    badge: "TOP 10",
    isPrime: true,
    year: 2024,
    duration: "45m",
    rating: "8.2",
    genre: "Reality TV",
  },
  {
    id: "original-2",
    title: "Being The Ricardos",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/being+the+ricardos.jpg",
    badge: "NEW SERIES",
    isPrime: true,
    year: 2024,
    duration: "42m",
    rating: "7.8",
    genre: "Comedy",
  },
  {
    id: "original-3",
    title: "Citadel",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/citadel.jpeg",
    badge: "NEW SERIES",
    isPrime: true,
    year: 2024,
    duration: "38m",
    rating: "8.5",
    genre: "Drama",
  },
  {
    id: "original-4",
    title: "Coming 2 America",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/coming+2+america.jpeg",
    badge: "NEW SEASON",
    isPrime: true,
    year: 2024,
    duration: "52m",
    rating: "9.1",
    genre: "Documentary",
  },
  {
    id: "original-5",
    title: "Fallout",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/fallout.webp",
    badge: "NEW SERIES",
    isPrime: true,
    year: 2024,
    duration: "44m",
    rating: "7.9",
    genre: "Action",
  },
]

export const recentlyAdded = [
  {
    id: "recent-1",
    title: "Final Destination 2",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/Final+Destination+2.jpg",
    isPrime: true,
    year: 2024,
    duration: "30m",
    rating: "8.7",
    genre: "Comedy-Drama",
  },
  {
    id: "recent-2",
    title: "Final Destination 4",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/Final+Destination+4.jpg",
    isPrime: true,
    year: 2024,
    duration: "1h 5m",
    rating: "8.4",
    genre: "Sci-Fi",
  },
  {
    id: "recent-3",
    title: "The Marvelous Show",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/the+marvelous+show.jpeg",
    isPrime: true,
    year: 2024,
    duration: "55m",
    rating: "8.1",
    genre: "Action",
  },
  {
    id: "recent-4",
    title: "Jack Ryan",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/Jack+Ryan.png",
    isPrime: true,
    year: 2024,
    duration: "58m",
    rating: "7.6",
    genre: "Drama",
  },
  {
    id: "recent-5",
    title: "Mission Impossible 1",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/MI+1.webp",
    isPrime: true,
    year: 2023,
    duration: "1h 51m",
    rating: "7.4",
    genre: "Biography",
  },
]

export const popularMovies = [
  {
    id: "movie-1",
    title: "Mission Impossible 7",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/MI7.jpg",
    badge: "TOP 10",
    isPrime: true,
    year: 2021,
    duration: "2h 18m",
    rating: "6.5",
    genre: "Action",
  },
  {
    id: "movie-2",
    title: "Mr and Mrs Smith",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/mr+ans+mrs+smith.jpg",
    isPrime: true,
    year: 2020,
    duration: "2h 0m",
    rating: "7.7",
    genre: "Drama",
  },
  {
    id: "movie-3",
    title: "Sound of metal",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/sound+of+metal.jpg",
    isPrime: true,
    year: 2021,
    duration: "1h 50m",
    rating: "5.3",
    genre: "Comedy",
  },
  {
    id: "movie-4",
    title: "The Bear",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/the+bear.jpeg",
    isPrime: true,
    year: 2021,
    duration: "2h 8m",
    rating: "6.8",
    genre: "Drama",
  },
  {
    id: "movie-5",
    title: "The Boys",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/the+boys.avif",
    isPrime: true,
    year: 2021,
    duration: "2h 11m",
    rating: "6.5",
    genre: "Biography",
  },
]

export const topTVShows = [
  {
    id: "tv-1",
    title: "The Marvelous Show",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/the+marvelous+show.jpeg",
    badge: "TOP 10",
    isPrime: true,
    year: 2024,
    duration: "1h 2m",
    rating: "8.7",
    genre: "Superhero",
  },
  {
    id: "tv-2",
    title: "The Power",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/the+power.webp",
    isPrime: true,
    year: 2023,
    duration: "52m",
    rating: "8.7",
    genre: "Comedy-Drama",
  },
  {
    id: "tv-3",
    title: "The Tommorrow War",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/The+tomorrow+war.png",
    isPrime: true,
    year: 2023,
    duration: "1h 8m",
    rating: "8.0",
    genre: "Action",
  },
  {
    id: "tv-4",
    title: "The Traitors",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/the+traitors.jpg",
    isPrime: true,
    year: 2023,
    duration: "1h 5m",
    rating: "7.1",
    genre: "Fantasy",
  },
  {
    id: "tv-5",
    title: "The Wheel of Time",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/the+wheelc+of+time.jpeg",
    isPrime: true,
    year: 2023,
    duration: "58m",
    rating: "6.5",
    genre: "Spy",
  },
]

// done till here

export const getContentById = (id: string) => {
  const allContent = [...recentlyAdded, ...popularMovies, ...topTVShows, ...featuredOriginals, featuredContent]
  return (
    allContent.find((item) => item.id === id) || {
      id,
      title: "Sample Content",
      description:
        "This is a sample description for the content. In a real application, this would be fetched from a database or API with detailed plot information and cast details.",
      thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/the+traitors.jpg",
      year: 2024,
      duration: "1h 30m",
      genre: "Drama, Thriller",
      rating: "TV-MA",
    }
  )
}

export const recommendedContent = [
  {
    id: "rec-1",
    title: "Similar Show 1",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/the+boys.avif",
    isPrime: true,
    year: 2024,
    duration: "45m",
    rating: "8.3",
    genre: "Drama",
  },
  {
    id: "rec-2",
    title: "Similar Show 2",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/The+tomorrow+war.png",
    isPrime: true,
    year: 2023,
    duration: "1h 2m",
    rating: "7.9",
    genre: "Thriller",
  },
  {
    id: "rec-3",
    title: "Similar Show 3",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/Jack+Ryan.png",
    isPrime: true,
    year: 2024,
    duration: "38m",
    rating: "8.1",
    genre: "Comedy",
  },
  {
    id: "rec-4",
    title: "Similar Show 4",
    thumbnail: "https://firestories.s3.ap-south-1.amazonaws.com/prime-images/fallout.webp",
    isPrime: true,
    year: 2024,
    duration: "52m",
    rating: "8.5",
    genre: "Action",
  },
]
